encoding: utf-8

baseurl: /technion_046195_2020_spring

collections:
  tutorials:
    output: true
#   tutorials_hb:
#     output: true
  workshops:
    output: true
  widgets:
    output: true

defaults:
- scope:
    path: "*/*/tutorial.md"
    type: "tutorials"
  values:
    layout: "tutorial"
    excerpt_separator: <!-- excerpt_end -->
    type: "tutorial"
- scope:
    path: "*/*/tutorial_slides.md"
    type: "tutorials"
  values:
    layout: "slides"
    type: "tutorial"
    slides: true
- scope:
    path: "*/*/tutorial_he.md"
    type: "tutorials"
  values:
    layout: "tutorial"
    excerpt_separator: <!-- excerpt_end -->
    type: "תרגול"
    hebrew: true
- scope:
    path: "*/*/tutorial_he_slides.md"
    type: "tutorials"
  values:
    layout: "slides"
    type: "תרגול"
    hebrew: true
    slides: true
- scope:
    path: "*/*/workshop_*.md"
    type: "workshops"
  values:
    layout: "tutorial"
    type: "workshop"
    excerpt_separator: <!-- excerpt_end -->
    render_with_liquid: false

exclude:
- "README.md"
- "LICENSE"
- "venv"
- "*/code/*"